version: '3.8'

services:

  backend:
    container_name: backend
    build: ./services/backend
    # build: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./services/backend/src:/app
      # - ./backend/src:/app
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000

  frontend:
    build: ./services/frontend
    # build: ./frontend
    depends_on:
      - backend
    volumes:
      - './services/frontend/app:/app'
      # - './frontend/app:/app'
      
      - '/app/node_modules'
    ports:
      - 3000:3000