version: '3.8'

services:
  frontend:
    # build: ./services/frontend
    image: jungfrau70/allegro-frontend:0.2
    # build: ./frontend
    volumes:
      # - './services/frontend/app:/app'
      - './frontend/app:/app'
      # - '/app/node_modules'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment: 
      - NODE_OPTIONS=--max-old-space-size=8192

