version: '3.8'

services:

  frontend:
    # build: ./services/frontend
    build: ./frontend
    volumes:
      # - './services/frontend:/app'
      - './frontend/app:/app'
      
      - '/app/node_modules'
    ports:
      - 3000:3000

