"""add models

Revision ID: 98fd5d0f8b2d
Revises: 7294f7c808d7
Create Date: 2022-10-16 16:25:10.823677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98fd5d0f8b2d'
down_revision = '7294f7c808d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
