# Choose the Image which has Node installed already
# FROM node:16.17.1-alpine as builder
FROM node:lts as builder

# make the 'app' folder the current working directory
WORKDIR /app

ENV NODE_OPTIONS=--openssl-legacy-provider

# copy both 'package.json' and 'package-lock.json' (if available)
COPY app/. .

# install project dependencies
RUN yarn install \
  --prefer-offline \
  --frozen-lockfile \
  --non-interactive \
  --production=false

# RUN yarn build

# RUN rm -rf node_modules && \
#   NODE_ENV=production yarn install \
#   --prefer-offline \
#   --pure-lockfile \
#   --non-interactive \
#   --production=true

# copy project files and folders to the current working directory (i.e. 'app' folder)

# FROM node:16.17.1-alpine
# FROM node:lts 

# WORKDIR /app

# COPY --from=builder /app  .

ENV HOST 0.0.0.0
EXPOSE 3000

CMD [ "yarn", "dev" ]